### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/joomla-browser#243]
The current release is 4.0.0 and this doesnt include numerous changes and optimisations.

Joomla-cms is using 4.0.0 so its wasting time testing ftp etc

Will there be a new release?

**Comment by Hackwar** [comment]
Codeception is really temperamental in regards to the tests and writing tests for it turned out to be complicated. That is why we looked into switching over to cypress and when you take a look at the CMS repo, you see a finalized PR there. We are currently working on documentation and will then replace codeception with cypress. That will make this project obsolete and I doubt that it will receive additional releases. At least don't expect major improvements here.

**Comment by brianteeman** [comment]
ok - fair enough

**Comment by puneet0191** [comment]
cypress is less complicated than Codeception 🤷‍♂️
